export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const QUERY_ALL_PRODUCTS = "QUERY_ALL_PRODUCTS";
export const QUERY_PRODUCT = "QUERY_PRODUCT"
export const UPDATE_SELECTED_PRODUCT = "UPDATE_SELECTED_PRODUCT"

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const ADD_USER = "ADD_USER";
export const QUERY_USER = "QUERY_USER";

export const UPDATE_TOTAL = "UPDATE_TOTAL";
export const UPDATE_CURRENT_QUANTITY = "UPDATE_CURRENT_QUANTITY";
